import type Database from "better-sqlite3";

export interface Company {
  name: string;
  slug: string;
  website: string;
  source?: "greenhouse" | "lever" | "ashby";
}

export const COMPANIES: Company[] = [
  // ── Greenhouse ──────────────────────────────────────────────────────────
  { name: "Airbnb", slug: "airbnb", website: "https://airbnb.com" },
  { name: "Stripe", slug: "stripe", website: "https://stripe.com" },
  { name: "Discord", slug: "discord", website: "https://discord.com" },
  { name: "DoorDash", slug: "doordash", website: "https://doordash.com" },
  { name: "Duolingo", slug: "duolingo", website: "https://duolingo.com" },
  { name: "Canva", slug: "canva", website: "https://canva.com" },
  { name: "Brex", slug: "brex", website: "https://brex.com" },
  { name: "Ramp", slug: "ramp", website: "https://ramp.com" },
  { name: "Rippling", slug: "rippling", website: "https://rippling.com" },
  { name: "Reddit", slug: "reddit", website: "https://reddit.com" },
  { name: "Plaid", slug: "plaid", website: "https://plaid.com" },
  { name: "Robinhood", slug: "robinhood", website: "https://robinhood.com" },
  { name: "Instacart", slug: "instacart", website: "https://instacart.com" },
  { name: "HubSpot", slug: "hubspot", website: "https://hubspot.com" },
  { name: "Asana", slug: "asana", website: "https://asana.com" },
  { name: "Airtable", slug: "airtable", website: "https://airtable.com" },
  { name: "Zapier", slug: "zapier", website: "https://zapier.com" },
  { name: "Twilio", slug: "twilio", website: "https://twilio.com" },
  { name: "Shopify", slug: "shopify", website: "https://shopify.com" },
  { name: "Intercom", slug: "intercom", website: "https://intercom.com" },
  { name: "Notion", slug: "notion", website: "https://notion.so" },
  { name: "Figma", slug: "figma", website: "https://figma.com" },
  { name: "Anthropic", slug: "anthropic", website: "https://anthropic.com" },
  { name: "Gusto", slug: "gusto", website: "https://gusto.com" },
  { name: "Amplitude", slug: "amplitude", website: "https://amplitude.com" },
  { name: "Mixpanel", slug: "mixpanel", website: "https://mixpanel.com" },
  { name: "Grammarly", slug: "grammarly", website: "https://grammarly.com" },
  { name: "Checkr", slug: "checkr", website: "https://checkr.com" },
  { name: "Faire", slug: "faire", website: "https://faire.com" },
  { name: "Zendesk", slug: "zendesk", website: "https://zendesk.com" },
  { name: "Okta", slug: "okta", website: "https://okta.com" },
  { name: "PagerDuty", slug: "pagerduty", website: "https://pagerduty.com" },
  { name: "Databricks", slug: "databricks", website: "https://databricks.com" },
  { name: "Confluent", slug: "confluent", website: "https://confluent.io" },
  { name: "Webflow", slug: "webflow", website: "https://webflow.com" },
  { name: "GitLab", slug: "gitlab", website: "https://gitlab.com" },
  { name: "Cloudflare", slug: "cloudflare", website: "https://cloudflare.com" },
  { name: "HashiCorp", slug: "hashicorp", website: "https://hashicorp.com" },
  { name: "Scale AI", slug: "scaleai", website: "https://scale.com" },
  { name: "Lattice", slug: "lattice", website: "https://lattice.com" },
  { name: "Superhuman", slug: "superhuman", website: "https://superhuman.com" },
  { name: "Stitch Fix", slug: "stitchfix", website: "https://stitchfix.com" },
  { name: "Chime", slug: "chime", website: "https://chime.com" },
  { name: "Marqeta", slug: "marqeta", website: "https://marqeta.com" },
  { name: "Affirm", slug: "affirm", website: "https://affirm.com" },
  { name: "Coinbase", slug: "coinbase", website: "https://coinbase.com" },
  { name: "Carta", slug: "carta", website: "https://carta.com" },
  { name: "dbt Labs", slug: "dbtlabs", website: "https://getdbt.com" },
  { name: "Datadog", slug: "datadoghq", website: "https://datadoghq.com" },
  { name: "Splunk", slug: "splunk", website: "https://splunk.com" },
  { name: "Replit", slug: "replit", website: "https://replit.com" },
  { name: "Monday.com", slug: "mondaydotcom", website: "https://monday.com" },
  { name: "Miro", slug: "miro", website: "https://miro.com" },
  { name: "Coda", slug: "coda", website: "https://coda.io" },
  { name: "ClickUp", slug: "clickup", website: "https://clickup.com" },
  { name: "Autodesk", slug: "autodesk", website: "https://autodesk.com" },
  { name: "Netlify", slug: "netlify", website: "https://netlify.com" },
  { name: "Fastly", slug: "fastly", website: "https://fastly.com" },
  { name: "Pulumi", slug: "pulumi", website: "https://pulumi.com" },
  { name: "Cohere", slug: "cohere", website: "https://cohere.com" },
  { name: "Character AI", slug: "character", website: "https://character.ai" },
  { name: "Runway", slug: "runwayml", website: "https://runwayml.com" },
  { name: "Weights & Biases", slug: "wandb", website: "https://wandb.ai" },
  { name: "OpenAI", slug: "openai", website: "https://openai.com" },
  { name: "Cursor", slug: "anysphere", website: "https://cursor.com" },
  { name: "Warp", slug: "warpdotdev", website: "https://warp.dev" },
  { name: "Framer", slug: "framer", website: "https://framer.com" },
  { name: "Greenhouse (Software)", slug: "greenhouse", website: "https://greenhouse.io" },
  { name: "Pendo", slug: "pendo", website: "https://pendo.io" },
  { name: "Productboard", slug: "productboard", website: "https://productboard.com" },
  { name: "Heap", slug: "heap", website: "https://heap.io" },
  { name: "FullStory", slug: "fullstory", website: "https://fullstory.com" },
  { name: "LaunchDarkly", slug: "launchdarkly", website: "https://launchdarkly.com" },
  { name: "Split.io", slug: "split", website: "https://split.io" },
  { name: "Persona", slug: "persona", website: "https://withpersona.com" },
  { name: "Segment (Twilio)", slug: "segment", website: "https://segment.com" },
  { name: "Hightouch", slug: "hightouch", website: "https://hightouch.com" },
  { name: "Census", slug: "census", website: "https://getcensus.com" },
  { name: "Coupa", slug: "coupa", website: "https://coupa.com" },
  { name: "BILL", slug: "bill", website: "https://bill.com" },
  { name: "Ripple", slug: "ripple", website: "https://ripple.com" },
  { name: "Fireblocks", slug: "fireblocks", website: "https://fireblocks.com" },
  { name: "Chainalysis", slug: "chainalysis", website: "https://chainalysis.com" },
  { name: "Aptos Labs", slug: "aptoslabs", website: "https://aptoslabs.com" },
  // ── Logistics / Supply Chain ────────────────────────────────────────────
  { name: "Flexport", slug: "flexport", website: "https://flexport.com" },
  { name: "Samsara", slug: "samsara", website: "https://samsara.com" },
  { name: "Project44", slug: "project44", website: "https://project44.com" },
  { name: "FourKites", slug: "fourkites", website: "https://fourkites.com" },
  { name: "Motive (KeepTruckin)", slug: "gomotive", website: "https://gomotive.com" },
  { name: "ShipBob", slug: "shipbob", website: "https://shipbob.com" },
  { name: "Shippo", slug: "shippo", website: "https://goshippo.com" },
  { name: "Stord", slug: "stord", website: "https://stord.com" },
  { name: "Turvo", slug: "turvo", website: "https://turvo.com" },
  { name: "Loadsmart", slug: "loadsmart", website: "https://loadsmart.com" },
  { name: "Flock Freight", slug: "flockfreight", website: "https://flockfreight.com" },
  { name: "Transfix", slug: "transfix", website: "https://transfix.io" },
  { name: "Platform Science", slug: "platformscience", website: "https://platformscience.com" },
  { name: "Flowspace", slug: "flowspace", website: "https://flowspace.com" },
  { name: "Ware2Go", slug: "ware2go", website: "https://ware2go.co" },
  { name: "Convoy", slug: "convoy", website: "https://convoy.com" },
  // ── Manufacturing / Mobility / Energy ───────────────────────────────────
  { name: "Rivian", slug: "rivian", website: "https://rivian.com" },
  { name: "Lucid Motors", slug: "lucidmotors", website: "https://lucidmotors.com" },
  { name: "Joby Aviation", slug: "jobyaviation", website: "https://jobyaviation.com" },
  { name: "Archer Aviation", slug: "archer", website: "https://archer.com" },
  { name: "Boom Supersonic", slug: "boomaero", website: "https://boomsupersonic.com" },
  { name: "Relativity Space", slug: "relativity", website: "https://relativityspace.com" },
  { name: "Rocket Lab", slug: "rocketlab", website: "https://rocketlabusa.com" },
  { name: "Planet Labs", slug: "planet", website: "https://planet.com" },
  { name: "Spire Global", slug: "spire", website: "https://spire.com" },
  { name: "Axiom Space", slug: "axiomspace", website: "https://axiomspace.com" },
  { name: "Danfoss", slug: "danfoss", website: "https://danfoss.com" },
  // ── Enterprise / B2B ────────────────────────────────────────────────────
  { name: "Veeva Systems", slug: "veeva", website: "https://veeva.com" },
  { name: "Tempus", slug: "tempus", website: "https://tempus.com" },
  { name: "Carbon Health", slug: "carbonhealth", website: "https://carbonhealth.com" },
  { name: "Hims & Hers", slug: "hims", website: "https://forhims.com" },
  { name: "Thirty Madison", slug: "thirtymadison", website: "https://thirtymadison.com" },
  { name: "Ro", slug: "roinc", website: "https://ro.co" },
  { name: "Flatiron Health", slug: "flatiron", website: "https://flatiron.com" },
  { name: "Ironclad", slug: "ironclad", website: "https://ironcladapp.com" },
  { name: "Sprinklr", slug: "sprinklr", website: "https://sprinklr.com" },
  { name: "Contentful", slug: "contentful", website: "https://contentful.com" },
  { name: "Algolia", slug: "algolia", website: "https://algolia.com" },
  { name: "Elastic", slug: "elastic", website: "https://elastic.co" },
  { name: "New Relic", slug: "newrelic", website: "https://newrelic.com" },
  { name: "Dynatrace", slug: "dynatrace", website: "https://dynatrace.com" },
  { name: "Celonis", slug: "celonis", website: "https://celonis.com" },
  { name: "ServiceNow", slug: "servicenow", website: "https://servicenow.com" },
  { name: "Workiva", slug: "workiva", website: "https://workiva.com" },
  { name: "Anaplan", slug: "anaplan", website: "https://anaplan.com" },
  { name: "Planful", slug: "planful", website: "https://planful.com" },

  // ── Lever ────────────────────────────────────────────────────────────────
  { name: "Lyft", slug: "lyft", website: "https://lyft.com", source: "lever" },
  { name: "Yelp", slug: "yelp", website: "https://yelp.com", source: "lever" },
  { name: "Eventbrite", slug: "eventbrite", website: "https://eventbrite.com", source: "lever" },
  { name: "Descript", slug: "descript", website: "https://descript.com", source: "lever" },
  { name: "Remote", slug: "remote", website: "https://remote.com", source: "lever" },
  { name: "Front", slug: "front", website: "https://front.com", source: "lever" },
  { name: "Benchling", slug: "benchling", website: "https://benchling.com", source: "lever" },
  { name: "Figma (Careers)", slug: "figma-1", website: "https://figma.com", source: "lever" },
  { name: "Coreweave", slug: "coreweave", website: "https://coreweave.com", source: "lever" },

  // ── Ashby ────────────────────────────────────────────────────────────────
  { name: "Vercel", slug: "vercel", website: "https://vercel.com", source: "ashby" },
  { name: "Linear", slug: "linear", website: "https://linear.app", source: "ashby" },
  { name: "Retool", slug: "retool", website: "https://retool.com", source: "ashby" },
  { name: "Mercury", slug: "mercury", website: "https://mercury.com", source: "ashby" },
  { name: "Loom", slug: "loom", website: "https://loom.com", source: "ashby" },
  { name: "Deel", slug: "deel", website: "https://deel.com", source: "ashby" },
  { name: "Ashby", slug: "ashby", website: "https://ashbyhq.com", source: "ashby" },
  { name: "Cal.com", slug: "cal-com", website: "https://cal.com", source: "ashby" },
  { name: "Knock", slug: "knock", website: "https://knock.app", source: "ashby" },
  { name: "Supabase", slug: "supabase", website: "https://supabase.com", source: "ashby" },
  { name: "Resend", slug: "resend", website: "https://resend.com", source: "ashby" },
];

export function seedCompanies(db: Database.Database) {
  const insert = db.prepare(
    "INSERT OR IGNORE INTO companies (name, greenhouse_slug, website_url, source) VALUES (?, ?, ?, ?)"
  );
  const insertMany = db.transaction((companies: Company[]) => {
    for (const c of companies) {
      insert.run(c.name, c.slug, c.website, c.source ?? "greenhouse");
    }
  });
  insertMany(COMPANIES);
}
